apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: kn-function-api
  namespace: {{ .Values.namespace }}
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.container_reposiroty }}/api:{{ .Values.docker_version }}
          env:
            - name: ES_ALIAS_RAW_DATA
              value: "smart-agriculture"
            - name: ES_ALIAS_SUMMARIZED_DATA
              value: "smart-agriculture-summarized"