image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  NO_PROXY: docker
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - setup_cluster_deploy
  - unit_test
  - dev_deploy
  - dev_e2e_test

# Pip's cache doesn't store the python packages https://pip.pypa.io/en/stable/reference/pip_install/#caching
# If you want to also cache the installed packages, you have to install them in a virtualenv and cache it as well.
cache:
  # Cache per branch
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - venv/

before_script:
  - apk update && apk fetch openjdk8
  - apk add --update coreutils # To update base64 in order to use option --decode
  - apk add --no-cache curl bash jq python3 py3-pip && apk add openjdk8 maven openssl
  - alias python=python3
  - curl https://sdk.cloud.google.com > install.sh # Download gcloud installer
  - bash install.sh --disable-prompts # Install gcloud
  - export PATH=$PATH:/root/google-cloud-sdk/bin # Add gcloud to PATH
  - echo $PRIVATE_KEY_FILE_CONTENT > /tmp/$CI_PIPELINE_ID.json
  - export CLOUDSDK_CORE_DISABLE_PROMPTS=1 # Equivalent to --quiet if does not work
  - export CLOUDSDK_CORE_PROJECT="$PROJECT_ID"
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud components install kubectl

after_script:
  - rm /tmp/$CI_PIPELINE_ID.json

# Run on all branches except setup-cluster
build:unit-test:
  stage: unit_test
  allow_failure: false
  except:
    - setup-cluster
  script:
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - chmod +x deploy/cicd_unit_test.sh
    - ./deploy/cicd_unit_test.sh

########################################################################################################################
# SETUP CLUSTER (Create branch setup-cluster at the beginning to create k8s cluster)
########################################################################################################################
setup_cluster:deploy:
  stage: setup_cluster_deploy
  allow_failure: false
  only:
    - setup-cluster
  script:
    - chmod +x deploy/cicd_setup_cluster_deploy.sh
    - ./deploy/cicd_setup_cluster_deploy.sh

########################################################################################################################
# MASTER
########################################################################################################################
dev:deploy:
  variables:
    ENVIRONMENT: dev
    DOCKER_VERSION: $CI_COMMIT_SHA
  stage: dev_deploy
  allow_failure: false
  only:
    - dev
    - master
  script:
    ## Get credentials for helm
    - gcloud container clusters get-credentials "$CLUSTER_NAME" --zone="$COMPUTE_ZONE" --project="$PROJECT_ID"
    ## Install helm
    - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
    - chmod 700 get_helm.sh
    - ./get_helm.sh
    ## Execute deployment
    - chmod +x deploy/cicd_deploy.sh
    - ./deploy/cicd_deploy.sh

dev:e2e-test:
  stage: dev_e2e_test
  allow_failure: false
  variables:
    ENVIRONMENT: dev
  only:
    - dev
    - master
  script:
    - chmod +x deploy/cicd_e2e.sh
    - ./deploy/cicd_e2e.sh
