FROM python:3.7

WORKDIR /app
ENV PYTHONPATH /app

COPY requirements.txt ./
COPY app.py ./

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

#CMD exec gunicorn --bind :8080 --workers 1 --threads 8 'app:app'
CMD exec gunicorn --access-logfile - --certfile=/etc/ssl/flask-hello/tls.crt --keyfile=/etc/ssl/flask-hello/tls.key --ssl-version TLS --bind :443 --workers 1 --threads 8 'app:app'

