apiVersion: v1
kind: Secret
metadata:
  name: flask-hello-certificates-secret
type: kubernetes.io/tls
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCRENDQWV3Q0NRQ09BSzJuNGJxWVdqQU5CZ2txaGtpRzl3MEJBUXNGQURCRU1Rc3dDUVlEVlFRR0V3SkcKVWpFUE1BMEdBMVVFQ2d3R1JuSmhibU5sTVE0d0RBWURWUVFMREFWemJXRnlkREVVTUJJR0ExVUVBd3dMWm14aApjMnN0YUdWc2JHOHdIaGNOTWpBd05ERTFNRGN4TWpReldoY05NekF3TkRFek1EY3hNalF6V2pCRU1Rc3dDUVlEClZRUUdFd0pHVWpFUE1BMEdBMVVFQ2d3R1JuSmhibU5sTVE0d0RBWURWUVFMREFWemJXRnlkREVVTUJJR0ExVUUKQXd3TFpteGhjMnN0YUdWc2JHOHdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFEYgpTZ00rVEcxOWM1cGJSUmdhUW8zMEIxakpTelhMeEtaRDVIbjhkVWRaZmh3dkpXZWg3dFd2RWdRSkx1VXNhMjh2CmU4QVdrNHZNTURZTjNmNElTUjZsdXdISTFVVDlqTW9uQWVqL2ZieXM0Zmk4T0hlOGhyUGMyelZabUFRNEFQeXYKdDdKT3B1SDdodXJISmlvMWZ6VVlnUGN6dGRjTGJuMWt1RnN5S2I1aHFVUEZrOWE0L1k5bHNLc0phcllJYW1obQpPamNJcThVRHRhRFhSL1RjQkJjQm5pWFBBR2ZjN0RJcmVNY2dlMnA4UVd5YTNIQlR5azZsdUN1SUhEVjRPaHFDCmY0a1Q2ODdOV2hxdFFlL0hjbGNGVC9OTkNBQXNLNUMyVzllNUVUY1ZucTQxcDZBL1J6OU5ISlFqUFowUWp5bGwKMkNQM3RCb1VaM1J0MGcvbWJYUUhBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFM1Y4QU9wRHgyOQpCQXd6dTZ3L2pIbm1QWnpJNzNJS3grV0RwalIzOGxlUVNlTktjblhsL3lXRkZIWDZadXEvbEN0ZnhhUVRRWEk1CnB0MGltTisrOVB1RWFhSVFndHZWQUZxTE53MkJ4eWJhYSs5emp0Slhxa0oyK1QrSG81MzJUUUJUSG10ZXFDZUQKZGMzUTRwdUFOSWhRbUJxL3JJUUlsZ01uVWRMQ0pSMEEyNVJuMW10OVNLY0tqRVp6Z29UQUNjWDkySWRCaStFbQpJZlVucy9waGZ5T3k1YnVmcXBITzZUR2l3cWF6Y3drTENxczdzeHpEbzR1aTBRVmdaaWw4ZStEbmp2VTU1OTY2ClJTSFJWUEQ4QVNmdk5XOXNTL0Yxckdnd3dvU3IzaXJVd2dDUW1hdk5pM3hwbmk4WkExT2N3QXFZQXlJekFQanoKczVaVExBNVNIeE09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLekNDQWhPZ0F3SUJBZ0lKQUkwb0RHaTJDekFiTUEwR0NTcUdTSWIzRFFFQkJRVUFNRVF4Q3pBSkJnTlYKQkFZVEFrWlNNUTh3RFFZRFZRUUtEQVpHY21GdVkyVXhEakFNQmdOVkJBc01CWE50WVhKME1SUXdFZ1lEVlFRRApEQXRtYkdGemF5MW9aV3hzYnpBZUZ3MHlNREEwTVRVd056RXlORFZhRncwek1EQTBNVE13TnpFeU5EVmFNRVF4CkN6QUpCZ05WQkFZVEFrWlNNUTh3RFFZRFZRUUtEQVpHY21GdVkyVXhEakFNQmdOVkJBc01CWE50WVhKME1SUXcKRWdZRFZRUUREQXRtYkdGemF5MW9aV3hzYnpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQwpnZ0VCQU96d1JONzBIeTRjckhqV2J2T0VURE5wZVBkQVo2ajUyNG9HMVkrRHNNdmxpRmo1OWVmakRqQmNiTWtlCmlvdGk5Q0k5T2NKeHR3c0JVT2xPZU9RRWtsOVA0TXhmMHJabTIxaCtidDljWGFObFNPRGZWcll6MmxwOUN6SjIKd2VIN2JNa1RWT0RMSzVYMmNXTmF6R1N3LzI3NS9yWTJYNjJIbjJQUUxSNFZYcmk4djE0ZUVLL2JMb0lWamJQQQozTDZTS0J1OXZ0aHRzbkVPZEJJSWdXT2pudVRPM25lQktJQnZVRXhodVl4QjBnK3BnWnEvbTJtTjZhUHZjajhiCmZXMVV5R1ZnNU5ja0JGTFRtMkVpVktZS2xxUXBVYXRvVndVSWN5VDd3U2plTEFFQ25QL3o3Z2E4M3pWNW9Yd0kKdmlLSmtVT3IwZE1SSk1FdzdteWMrU1VLNW44Q0F3RUFBYU1nTUI0d0hBWURWUjBSQkJVd0U0SUxabXhoYzJzdAphR1ZzYkcrSEJDUEdvWWt3RFFZSktvWklodmNOQVFFRkJRQURnZ0VCQUdQTlo3MVptVHNiSk1mZkVIMXVEcU5ZCi9SN256VzdSdlZ1UVdLdnoxRmxWQi9jMDg1Zms5cW1FQWJob0FGR0tWWkFPZ3VEVEF6dDhHMFk4UmdCYlR3RUYKYjhTMmJwOFRqTnZXbnRLTjdjTWgzaXFkK25oTHp6Q1pEVmFQYjdYNzB0QnUvNTBRQnhIa1lmYldJcmpKMFR0cgoyYittdXJ3M2JaczYxZHY3U3h4bTVpb2pKL2dqdGpNUCs5WlMyVU1wbXErdU5WMlhqTVcxZ25sQUtDK2pOSlNJCnJFcGF3Y1p1dEZQVk02cGRJaGc3d3J4THZIVnNlaHhKT3d2QkhtVjVXRVMybG5sRCtBSld6U0tHeHRXcnZhRXAKeStYK3gwaHZOOHdFUFFwMDNUWGNOeTlmeHlEUVdtR1MrdlB3MUwvSGdtK3RUVC9kTjVRem5DcnU5cG9vNVZRPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBN1BCRTN2UWZMaHlzZU5adTg0Uk1NMmw0OTBCbnFQbmJpZ2JWajRPd3krV0lXUG4xCjUrTU9NRnhzeVI2S2kyTDBJajA1d25HM0N3RlE2VTU0NUFTU1gwL2d6Ri9TdG1iYldINXUzMXhkbzJWSTROOVcKdGpQYVduMExNbmJCNGZ0c3lSTlU0TXNybGZaeFkxck1aTEQvYnZuK3RqWmZyWWVmWTlBdEhoVmV1THkvWGg0UQpyOXN1Z2hXTnM4RGN2cElvRzcyKzJHMnljUTUwRWdpQlk2T2U1TTdlZDRFb2dHOVFUR0c1akVIU0Q2bUJtcitiCmFZM3BvKzl5UHh0OWJWVElaV0RrMXlRRVV0T2JZU0pVcGdxV3BDbFJxMmhYQlFoekpQdkJLTjRzQVFLYy8vUHUKQnJ6Zk5YbWhmQWkrSW9tUlE2dlIweEVrd1REdWJKejVKUXJtZndJREFRQUJBb0lCQURDcmNob3lIeTJEcWxIdwpDajV2VUkvRy9KZ2RYSzJ6RlV1Vzk4dFJDOEgyVmptZ3JzaUJOV3J0c1ZMbXVTTEVvczFkc2oya3lpcXlqSUpBCklra0VQMlRnclphTm9HVGpYKzhmbVhxOEtHZmw2RUI0NEFEeFNjc0lvSUl2THNoU3N4ZmlwcTYrVFNleXhidlkKN045S0ZFNGhnQmJCdUltV3NFRDZoQ29IemJzNGRRZlVWSXJ2WHR0ZndmVk5qWGgxZjdqZmpYMnV3aGJDcG04dAp6dFloTFpzaitZaEQxWmdpMUthWWc1bU9FNlNHVjhQaFhWQVBEdTNxM2RCVHB2Q2tuU2hxZHhMY29NMlZxNHB3CmtYWThEMVM4Z0E1TW1qcjMwMC9pZC9ja2lRSWI0bisyWCtPL1dZSmZyY1FmRkROOEduZjJURGZabzM5SUcxTU8KV1ZBUmlvRUNnWUVBL01HTVFLZ05mVHF2cCtValArV25JcTl4bW5sNHlxTDBFNTYxaDVLNjJVVFhVbkhrZnNMZgptRDVaSlM5dGVhUTJvRlhIS3BvUjZHMnY0R3ZhblVnZVN6QzltWWpmZDhtcVhkcFVJNFBUNEpGbFFneC9qQTVXCnhWRkt5bmtVNTFhQ081d0NZaFdoYmpLSkZQM3Y3eXlyckhLd0VJM0hGSVlsRVk3RFl3ZHZPSjhDZ1lFQTcvckEKVzZBZ2tnQnFzOW1BbmVsN1pCUitPWDVudXoxVjRDc2lCdkJKUkVURm1NdmowMCtqVkRxcGZrMWJNQVJxN1BENAozOWI0UnhrVXRpbDcvaVhVY1orKzlDOWFSYTBobk1KVE1mU0IxYW5meGFHaW5LWEwvaFQvZ1N3Umh5eG51VGRhCkx0V3pLMDFpdUoxWURSaDRreWlGVVJ2TVRQMW5CQ3VyOEphVEppRUNnWUJodW9SOFMzNUx1WEZKdmJOUGRZQ1cKVExma1BxdVJ6a2dKZmdnNmoyVm50Tko4c2tUakxuNDk0MzJjZnlZWkxvRmdwVW9KRXVGeHVWZVRzcUFveUVYTwpWTjQ2aTAyOGgyRTBRTUxmcUkwMyszL25kZVdyUmJBUFEwdGoxa1ZhM1h3bGlFRHpvK0Z6Tmw4Q210MDI0VkxQCnJ0aWN6ZlQzM3BaZW41QzByWjgzaVFLQmdRQ0UxR055azlCVFgvMnZyTjAvQ3NRc29oYzMxWnF2RGdVaGZsNW8KUHNvZkNuM2cxRUkzYldZM01mMHRGcjQ1ZHNpRWUrRVZiTlNoN2VVRDZ6UmhlU2o4OTNIbmtPcERsTS85QjZhcgpDTzV3aUlWK3k3ZkpReEFGaERQa21MTGZBaG9yYjlMd0I0TVRuZExkNHVHZzVnR2ZXcGRvVEoycG83MUlscSttCkRJSklZUUtCZ1FDZDJGd2VzMGJvSFQza2c3S2lOb3RGUTRoZ2IxTGRHQmJpZytsallhM1FHQW1ucjJNRmpLZXAKTCtXSkIrVGZabGg3UE9peTJEbHg0S09pQzFWZkovUWU1Q0twdnMyUitVSW13MmVxRTh5aHR6ZTZaZlR0dXE2MQozeXlkOGRqMnFmNzJSellnSWNadE5PYWdiODIybkE5L1YxaGI0dmpPTFo2M2lSYnkyZEt3T3c9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-hello
  template:
    metadata:
      labels:
        app: flask-hello
    spec:
      containers:
        - name: flask-hello
          image: eu.gcr.io/ysennoun-iot/flask-hello:latest
          volumeMounts:
            - name: flask-hello-certificates
              mountPath: /etc/ssl/flask-hello/
              readOnly: true
      volumes:
        - name: flask-hello-certificates
          secret:
            secretName: flask-hello-certificates-secret

---

apiVersion: v1
kind: Service
metadata:
  name: flask-hello
spec:
  type: LoadBalancer
  selector:
    app: flask-hello
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443