apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  access_key: {{ .Values.s3aAccessKey }}
  secret_key: {{ .Values.s3aSecretKey }}