apiVersion: v1
kind: Secret
metadata:
  name: vernemq-certificates-secret
  namespace: {{ .Values.namespace }}
type: kubernetes.io/tls
data:
  ca.crt: {{ .Values.mqttCA }}
  tls.crt: {{ .Values.mqttTLS }}
  tls.key: {{ .Values.mqttKey }}

---

apiVersion: v1
kind: Secret
metadata:
  name: vernemq-user-indexer
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: aW5kZXhlcgo= #indexer in base64
  password: M3l3YkNzMnVCNAo=

---

apiVersion: v1
kind: Secret
metadata:
  name: vernemq-user-notifier
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: bm90aWZpZXIK #notifier in base64
  password: cXZRc1NwZzN0awo=
