apiVersion: v1
kind: Pod
metadata:
  name: mqtt-client
  namespace: {{ .Values.namespace }}
  labels:
    purpose: demonstrate-mqtt-client
spec:
  containers:
    - name: mqtt-client
      image: {{ .Values.containerReposiroty }}/mqtt-client:{{ .Values.dockerVersion }}
      env:
        - name: SERVICE_NAME
          value: "vernemq-cluster"
        - name: NAMESPACE_NAME
          value: "default"
        - name: TOPIC_NAME
          value: "iot/farming"
        - name: PORT
          value: "1883"
        - name: KN_FUNCTION_NAME
          value: "iot-kn-function"
        - name: ISTIO_INGRESS_GATEWAY_IP_ADDRESS
          value: {{ .Values.istioIngressGatewayIpAddress }}
        - name: BROKERS_URL
          value: "http://broker-indexer."{{ .Values.namespace }}".svc.cluster.local/,http://broker-notification."{{ .Values.namespace }}".svc.cluster.local/"
        - name: CE-Type
          value: "dev.knative.last.value"