apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
 name: iot-kn-function-api-historical
 namespace: default
spec:
 template:
   spec:
     containers:
       - image: ${CONTAINER_REPOSITORY}/${PROJECT_NAME}/ot-kn-function-api-historical:latest
