FROM maven:3.3-jdk-8

WORKDIR /app
COPY code/historical-jobs/ /app
RUN mvn clean package
RUN wget https://apache.mirrors.benatherton.com/spark/spark-2.4.4/spark-2.4.4.tgz
RUN tar -zxvf spark-2.4.4.tgz
CMD spark-2.4.4/bin/spark-submit \
    --master k8s://https://${K8S_APISERVER_HOST}:${K8S_APISERVER_PORT} \
    --deploy-mode cluster \
    --name spark-json-to-parquet \
    --class com.xebia.iot.main.Main \
    --conf spark.executor.instances=2 \
    --conf es.index.auto.create=true \
    --conf es.nodes=${ES_NODES} \ mon-service.mon-namespace.svc.cluster.local
    --conf es.port=${ES_PORT} \
    --conf fs.s3a.endpoint=${FS_S3A_ENDPOINT} \
    --conf spark.kubernetes.container.image=${CONTAINER_REPOSITORY}/spark-on-docker:2.4.4 \
    local:///app/target/historical-jobs-1.0-SNAPSHOT-jar-with-dependencies.jar ${INCOMING_ALIAS} $${PREPARED_DATA_PATH} "EsToParquet"