FROM python:3.7

WORKDIR /app
ENV PYTHONPATH /app

COPY applications/python-code/requirements.txt ./
COPY applications/python-code/src /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD [ "python", "iot/kn_function_main.py" ]