FROM debian:jessie
MAINTAINER Yassir sennoun, ysennoun@xebia.fr

# Install system requirements
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget && \
    curl && \
    apt-get autoremove -y && \
    apt-get clean

# Install mosquitto clients
RUN apt-get update && apt-get install -y mosquitto-clients