FROM python:3.7

WORKDIR /app
ENV PYTHONPATH /app

COPY code/serverless/requirements.txt ./
COPY code/serverless/src /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD [ "python", "mqtt/mqtt_client.py" ]