apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
        - name: front-end
          image: {{ .Values.containerRepository }}/front-end:{{ .Values.dockerVersion }}
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: front-end
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.frontEndIp }}
  selector:
    app: front-end
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
