FROM python:3.7

WORKDIR /app
ENV PYTHONPATH /app
ENV PORT 8080
EXPOSE $PORT

COPY applications/python-code/requirements.txt ./
COPY applications/python-code/src /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 iot.kn_function_main:app