apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      run: indexer
  replicas: 1
  template:
    metadata:
      labels:
        run: indexer
    spec:
      containers:
        - name: indexer
          image: {{ .Values.containerRepository }}/indexer:{{ .Values.dockerVersion }}
          env:
            - name: SERVICE_NAME
              value: {{ .Values.infrastructureRelease }}-vernemq
            - name: NAMESPACE_NAME
              value: {{ .Values.namespace }}
            - name: TOPIC_NAME
              value: "$share/indexer/iot/farming" # sharing topic "iot/farming between replicas
            - name: PORT
              value: "1883"
            - name: ELASTICSEARCH_ENDPOINT
              value: "elasticsearch-master:9200" #{{ .Values.infrastructureRelease }}-elasticsearch-master:9200
            - name: ES_ALIAS
              value: "smart-agriculture"
          ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  name: indexer
  namespace: {{ .Values.namespace }}
  labels:
    run: indexer
spec:
  ports:
    - port: 80
  selector:
    run: indexer

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: indexer
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: indexer
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50