FROM maven:3.3-jdk-8

WORKDIR /app
COPY code/historical-jobs/ /app
RUN mvn clean package
RUN wget https://apache.mirrors.benatherton.com/spark/spark-2.4.4/spark-2.4.4.tgz
RUN tar -zxvf spark-2.4.4.tgz
CMD spark-2.4.4/bin/spark-submit \
    --master k8s://https://${K8S_APISERVER_HOST}:${K8S_APISERVER_PORT} \
    --deploy-mode cluster \
    --name ${ENVIRONMENT}-spark-json-to-parquet \
    --class com.xebia.iot.main.Main \
    --conf spark.executor.instances=2 \
    --conf spark.kubernetes.container.image=${PROJECT_NAME}/${ENVIRONMENT}-spark-on-docker:2.4.4 \
    local:///app/target/historical-jobs-1.0-SNAPSHOT-jar-with-dependencies.jar ${INCOMING_DATA_PATH} ${RAW_DATA_PATH} ${PREPARED_DATA_PATH} "JsonToParquet"