apiVersion: eventing.knative.dev/v1alpha1
kind: Broker
metadata:
  name: broker-notification
  namespace: {{ .Values.namespace }}
  labels:
    serving.knative.dev/visibility: cluster-local

---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: kn-function-notification
  namespace: {{ .Values.namespace }}
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: {{ .Values.container_reposiroty }}/notification:{{ .Values.docker_version }}
            env:
              - name: THRESHOLD_TEMPERATURE
                value: "35"
              - name: THRESHOLD_HUMIDITY
                value: "10"
              - name: THRESHOLD_MOISTURE
                value: "70"
              - name: SMTP_PORT
                value: "465"
              - name: SMTP_SERVER
                value: "smtp.gmail.com"
              - name: SENDER_EMAIL
                value: "smartagriculturewithk8s@gmail.com"
              - name: RECEIVER_EMAIL
                value: "ysennoun@xebia.fr"
              - name: SENDER_PASSWORD
                value: "SmartAgricultureWithK8S"

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: trigger-notification
  namespace: {{ .Values.namespace }}
spec:
  filter:
    attributes:
      type: dev.knative.notification
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: kn-function-notification