FROM python:3.7

WORKDIR /app
ENV PYTHONPATH /app

COPY code/serverless/requirements.txt ./
COPY code/serverless/src/common /app/common
COPY code/serverless/src/application/indexer /app/application/indexer

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD [ "python", "application/indexer/mqtt_main.py" ]