apiVersion: v1
kind: Pod
metadata:
  name: put-jars-in-minio-{{ .Values.timestamp }}
  namespace: {{ .Values.namespace }}
  labels:
    name: put-jars-in-minio
spec:
  containers:
    - name: put-jars-in-minio-{{ .Values.timestamp }}
      image: {{ .Values.containerRepository }}/put-jars-in-minio:{{ .Values.dockerVersion }}
      env:
        - name: MINIO_ENDPOINT
          value: https://smart-agriculture-minio:9000
        - name: MINIO_BUCKET_NAME
          value: "bucket"
        - name: MINIO_OBJECT_PREFIX
          value: "jars/"
        - name: MINIO_ACCESS_KEY_PATH
          value: "bucket"
        - name: MINIO_ACCESS_KEY_PATH
          value: "/etc/minio/access_key"
        - name: MINIO_SECRET_KEY_PATH
          value: "/etc/minio/secret_key"
      volumeMounts:
        - name: minio-secret-volume
          mountPath: /etc/minio/
          readOnly: true
  volumes:
    - name: minio-secret-volume
      secret:
        secretName: minio-secret
  restartPolicy: Never