apiVersion: v1
kind: Pod
metadata:
  name: iot-mqtt-client
  labels:
    purpose: demonstrate-iot-mqtt-client
spec:
  containers:
  - name: iot-mqtt-client
    image: ${CONTAINER_REPOSITORY}/${PROJECT_NAME}/ot-mqtt-client:1.0.1
    env:
    - name: SERVICE_NAME
      value: "vernemq-cluster"
    - name: NAMESPACE_NAME
      value: "default"
    - name: TOPIC_NAME
      value: "iot/farming"
    - name: PORT
      value: "1883"
    - name: KN_FUNCTION_NAME
      value: "iot-kn-function"
    - name: ISTIO_INGRESS_GATEWAY_IP_ADDRESS
      value: "10.64.3.62" #"${ISTIO_INGRESS_GATEWAY_IP_ADDRESS}"
    - name: BROKERS_URL
      value: "http://iot-broker-last-value-broker.default.svc.cluster.local/"
    - name: CE-Type
      value: "dev.knative.last.value"