FROM python:3.7

WORKDIR /app
ENV PYTHONPATH /app

COPY code/serverless/requirements.txt ./
COPY code/serverless/src/common /app/common
COPY code/serverless/src/api /app/api

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 api.kn_serving_main:app