FROM python:3.7

WORKDIR /app
ENV PYTHONPATH /app

COPY code/serverless/requirements.txt ./
COPY code/serverless/src /app #TODO only api not all code

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 api.kn_function_main:app