apiVersion: networking.k8s.io/v1beta1 #https://knative.dev/docs/reference/serving-api/#networking.internal.knative.dev%2fv1alpha1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/auth-type: basic
    #nginx.ingress.kubernetes.io/auth-secret: basic-auth
    #nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required - foo'
spec:
  rules:
    - http:
        paths:
          - path: /(.*)
            backend:
              serviceName: kn-serving-api
              servicePort: 8080