FROM docker:stable

RUN apk add --no-cache curl python py-pip

WORKDIR /app
ENV PYTHONPATH /app

COPY code/serverless/requirements.txt ./
COPY code/serverless/src /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 storage.historical.kn_function_main:app