FROM python:3.7

WORKDIR /app
ENV PYTHONPATH /app

COPY code/redis-to-minio/requirements.txt ./
COPY code/redis-to-minio/src /app

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD [ "python", "main.py" ]